test: cram tests for CLI (without server) (#20)
* test: cram tests for CLI (without server)

* ci: lint dep bounds

* test: update cmdliner and cram tests

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -66,3 +66,17 @@ jobs:
       - name: Install dependencies
         run: opam install -y opam-dune-lint
       - uses: ocaml/setup-ocaml/lint-opam@v3
+
+  lint-dep-bounds:
+    runs-on: ubuntu-latest
+    if: contains(github.event.pull_request.labels.*.name, 'ready')
+
+    steps:
+      - name: Checkout tree
+        uses: actions/checkout@v6
+      - name: Check all dependencies have lower bounds
+        run: |
+          awk '/^depends:/,/^\]/' bondi.opam \
+            | grep -E '^\s+"[a-z]' \
+            | grep -v -e '>=' -e 'with-doc' \
+            | { if read -r line; then echo "::error::Dependencies missing lower bounds:"; echo "$line"; cat; exit 1; fi; }
